
package server.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MoviesService", targetNamespace = "http://service.server/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MoviesService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server/MoviesService/insertMovieRequest", output = "http://service.server/MoviesService/insertMovieResponse")
    public boolean insertMovie(
        @WebParam(name = "arg0", partName = "arg0")
        Movie arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns server.service.Movie
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server/MoviesService/updateMovieRequest", output = "http://service.server/MoviesService/updateMovieResponse")
    public Movie updateMovie(
        @WebParam(name = "arg0", partName = "arg0")
        Movie arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server/MoviesService/getMoviesRequest", output = "http://service.server/MoviesService/getMoviesResponse")
    public String getMovies();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.server/MoviesService/deleteMovieRequest", output = "http://service.server/MoviesService/deleteMovieResponse")
    public boolean deleteMovie(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
