
package server.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MoviesServiceImplService", targetNamespace = "http://service.server/", wsdlLocation = "http://localhost:8080/movies/MoviesServiceImpl?wsdl")
public class MoviesServiceImplService
    extends Service
{

    private final static URL MOVIESSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MOVIESSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName MOVIESSERVICEIMPLSERVICE_QNAME = new QName("http://service.server/", "MoviesServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/movies/MoviesServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOVIESSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        MOVIESSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public MoviesServiceImplService() {
        super(__getWsdlLocation(), MOVIESSERVICEIMPLSERVICE_QNAME);
    }

    public MoviesServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOVIESSERVICEIMPLSERVICE_QNAME, features);
    }

    public MoviesServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, MOVIESSERVICEIMPLSERVICE_QNAME);
    }

    public MoviesServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOVIESSERVICEIMPLSERVICE_QNAME, features);
    }

    public MoviesServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MoviesServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MoviesService
     */
    @WebEndpoint(name = "MoviesServiceImplPort")
    public MoviesService getMoviesServiceImplPort() {
        return super.getPort(new QName("http://service.server/", "MoviesServiceImplPort"), MoviesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoviesService
     */
    @WebEndpoint(name = "MoviesServiceImplPort")
    public MoviesService getMoviesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.server/", "MoviesServiceImplPort"), MoviesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOVIESSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw MOVIESSERVICEIMPLSERVICE_EXCEPTION;
        }
        return MOVIESSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
